# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  #imports =
  #  [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  #  ];
  imports =
     [
       <nixpkgs/nixos/modules/profiles/all-hardware.nix>
       <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
     ];

  # Use the systemd-boot EFI boot loader.
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/disk/by-id/usb-ZALMAN_ZM-VE350_WXT1EC0HDWX8-0:1";

  #boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "sr_mod" ];
  #boot.initrd.kernelModules = [ ];
  #boot.kernelModules = [ "kvm-amd" ];
  #boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nix-portable";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
 
}
