# Not autogenerated, so you should add stuff here. But not too much, just the hardware-scan releated. Others go into devices/portable
{ config, lib, pkgs, ... }:

{
  imports =
     [
       <nixpkgs/nixos/modules/profiles/all-hardware.nix>
       <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
     ];

  #boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "sr_mod" ];
  #boot.initrd.kernelModules = [ ];
  #boot.kernelModules = [ "kvm-amd" ];
  #boot.extraModulePackages = [ ];

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
